name: Nightly Sitemap Generator

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate sitemap.xml in root
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          find . -name index.html | grep -v '/\.' | while read filename; do
            url="https://epicairise.github.io${filename#./}"
            echo "  <url><loc>$url</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

                - name: Commit and Push Sitemap
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin main
          git checkout main
          mv sitemap.xml ./sitemap.xml  # Just in case it's not in root
          git add sitemap.xml --force
          git commit -m "Add sitemap.xml to root" || echo "No changes to commit"
          git remote set-url origin https://epicairise:${GH_PAT}@github.com/epicairise/epicairise.github.io.git
          git push origin main


     
