name: Nightly Sitemap Generator


on:
  schedule:
    - cron: '0 5 * * *'      # Runs daily at 5:00 AM UTC
  workflow_dispatch:         # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in $(find . -name "*.html"); do
            clean_path=${file#./}
            url="https://dir.querygap.com/${clean_path}"
            echo "  <url><loc>$url</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap with all pages" || echo "No changes"
          git push

      - name: Ping search engines
        run: |
          curl "https://www.google.com/ping?sitemap=https://dir.querygap.com/sitemap.xml"
          curl "https://www.bing.com/ping?sitemap=https://dir.querygap.com/sitemap.xml"
