      - name: Commit and Push Sitemap
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || exit 0
          git remote set-url origin https://epicairise:${GH_PAT}@github.com/epicairise/epicairise.github.io.git
          git push origin main
